services:
  mysql:
    container_name: 'mygamelist'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mygamelist'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=mies'
    ports:
      - '3306:3306'